
spring:
  application:
    name: config-server
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: file:///D:/Practise_and_Developments/SpringBoot/cloud-config-server
server:
  port: 8888