server:
  port: 8090

spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      default-filters:
        - AddRequestHeader=Custom-Header, CustomValue
      routes:
        - id: product-service
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/product-service/**

        - id: order-service
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/order-service/**

        - id: customer-service
          uri: lb://CUSTOMER-SERVICE
          predicates:
            - Path=/customer-service/**
    discovery:
      locator:
        enabled: true # Enable service discovery for routing
        lower-case-service-id: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/ # Eureka Server URL
