spring:
  cloud:
    gateway:
      default-filters:
        - AddRequestHeader=Custom-Header, CustomValue
      routes:
        - id: product-service
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/product-service/**
          filters:
            - name: CircuitBreaker
              args:
                name: productService
                fallbackuri: forward:/fallback/product

        - id: order-service
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/order-service/**
          filters:
            - name: CircuitBreaker
              args:
                name: orderService
                fallbackuri: forward:/fallback/order

        - id: customer-service
          uri: lb://CUSTOMER-SERVICE
          predicates:
            - Path=/customer-service/**
          filters:
            - name: CircuitBreaker
              args:
                name: customerService
                fallbackuri: forward:/fallback/customer

        - id: gateway-security
          uri: lb://GATEWAY-SECURITY
          predicates:
            - Path=/gateway-security/**
          filters:
            - name: CircuitBreaker
              args:
                name: gatewaySecurity
                fallbackuri: forward:/fallback/security
    discovery:
      locator:
        enabled: true # Enable service discovery for routing
        lower-case-service-id: true

management:
  endpoint:
    health:
      show-details: always
    hystrix:
      stream:
        enabled: true

hystrix:
  threadpool:
    productServiceThreadPool:
      coreSize: 10 # Thread pool size for product service
      maxQueueSize: 5 # Queue size limit
    orderServiceThreadPool:
      coreSize: 10 # Thread pool size for order service
      maxQueueSize: 5 # Queue size limit
    customerServiceThreadPool:
      coreSize: 10 # Thread pool size for customer service
      maxQueueSize: 5 # Queue size limit

  command:
    fallbackcmd:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000
          strategy: THREAD  # Use THREAD for thread isolation (bulkhead)
        isolationStrategy: THREAD
      circuitBreaker:
        requestVolumeThreshold: 10
        sleepWindowInMilliseconds: 10000
        errorThresholdPercentage: 50

