spring:
  cloud:
    gateway:
      default-filters:
        - AddRequestHeader=Custom-Header, CustomValue
      routes:
        - id: product-service
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/product-service/**
          filters:
            - name: CircuitBreaker
              args:
                name: productService
                fallbackuri: forward:/fallback/product

        - id: order-service
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/order-service/**
          filters:
            - name: CircuitBreaker
              args:
                name: orderService
                fallbackuri: forward:/fallback/order

        - id: customer-service
          uri: lb://CUSTOMER-SERVICE
          predicates:
            - Path=/customer-service/**
          filters:
            - name: CircuitBreaker
              args:
                name: customerService
                fallbackuri: forward:/fallback/customer
    discovery:
      locator:
        enabled: true # Enable service discovery for routing
        lower-case-service-id: true

management:
  endpoint:
    health:
      show-details: always
    hystrix:
      stream:
        enabled: true

hystrix:
  command:
    fallbackcmd:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000
      circuitBreaker:
        requestVolumeThreshold: 10
        sleepWindowInMilliseconds: 10000
        errorThresholdPercentage: 50

